// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rDh6K8-sBZXig6HyamXZW76-iJk8UF8',
    appId: '1:610830926894:web:e08b3c87dc45bc0d608bbf',
    messagingSenderId: '610830926894',
    projectId: 'our-app-02025',
    authDomain: 'our-app-02025.firebaseapp.com',
    storageBucket: 'our-app-02025.firebasestorage.app',
    measurementId: 'G-L8QBE43FKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS0qYJ_m-Pt8KGpljNuUxZVzHHrMCumxM',
    appId: '1:610830926894:android:7e81a483650128d7608bbf',
    messagingSenderId: '610830926894',
    projectId: 'our-app-02025',
    storageBucket: 'our-app-02025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7p61QDxuIf4grFujewg3xWupl6GOjysw',
    appId: '1:610830926894:ios:cc8090e49f5c31a7608bbf',
    messagingSenderId: '610830926894',
    projectId: 'our-app-02025',
    storageBucket: 'our-app-02025.firebasestorage.app',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7p61QDxuIf4grFujewg3xWupl6GOjysw',
    appId: '1:610830926894:ios:cc8090e49f5c31a7608bbf',
    messagingSenderId: '610830926894',
    projectId: 'our-app-02025',
    storageBucket: 'our-app-02025.firebasestorage.app',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8rDh6K8-sBZXig6HyamXZW76-iJk8UF8',
    appId: '1:610830926894:web:ee3ba2c5766d6b89608bbf',
    messagingSenderId: '610830926894',
    projectId: 'our-app-02025',
    authDomain: 'our-app-02025.firebaseapp.com',
    storageBucket: 'our-app-02025.firebasestorage.app',
    measurementId: 'G-TH85L66E5F',
  );
}
